server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
        namespace: 89f0c9d8-b2b2-4c20-983b-7a7d4a7470f2
    gateway:
      routes:
        - id: user-service-gateway
          predicates:
            - Path=/user/**
          uri: lb://userservice
        - id: order-service-gateway
          predicates:
            - Path=/order/**
          uri: lb://orderservice
