server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
        namespace: 89f0c9d8-b2b2-4c20-983b-7a7d4a7470f2
    gateway:
      routes:
        - id: user-service-gateway
          predicates:
            - Path=/user/**
          uri: lb://userservice
        - id: order-service-gateway
          predicates:
            - Path=/order/**
          uri: lb://orderservice
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://192.168.200.130:15672"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期