server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://192.168.200.130:3306/cloud_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
        namespace: 89f0c9d8-b2b2-4c20-983b-7a7d4a7470f2
  rabbitmq:
    host: 192.168.200.130
    port: 5672
    virtual-host: /
    username: itcast
    password: 123321
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS